export const ptText = {
    headerHome: "INÍCIO",
    headerAbout: "SOBRE",
    headerProjects: "PROJETOS",
    headerContact: "CONTATO",
    homeMe: "Oi. Eu sou Guilherme Cantarino.",
    homeTitle: "Desenvolvedor Front-End.",
    homeKnowMe: "Me conheça",
    aboutH2: "SOBRE",
    aboutDescription: "Sou uma pessoa apaixonada por tecnologia e ainda mais apaixonada por aprender. Em meados de 2022 comecei a me especializar em desenvolvimento front-end. Possuo uma base forte e estou sempre tentando aprender novas tecnologias, me aperfeiçoar nas tecnologias que já uso e melhorar a forma como eu organizo e escrevo meu código no geral. Além disso, sou uma pessoa extremamente dedicada, responsável e organizada, e tenho prazer em dar o meu melhor em tudo que faço. Estou buscando minha primeira experiência profissional, como uma forma de desenvolver ainda mais minhas habilidades e contribuir no desenvolvimento de produtos que sejam úteis para as pessoas.",
    aboutStackTitle: "Stack Tecnológico & Ferramentas",
    projectsH2: "PROJETOS",
    projectsDesc1: "Feito com React.js e utilizando Firebase para o Back-End. Protótipo de uma plataforma de streaming altamente inspirada pela Netflix.",
    projectsDesc2: "Feito com React.js. Esse projeto consiste em um gerador de Curriculum Vitae. O usuário insere suas informações e a aplicação gera um Curriculum Vitae em formato pdf. O usuário também pode inserir quantas experiências educacionais e profissionais desejar.",
    projectsDesc3: "Feito com React.js e utilizando Firebase para o Back-End. Implementação de um jogo similar a 'Onde Está Wally?' com temática da Marvel Comics. Há uma foto com vários super heróis e o jogador precisa encontrar três específicos. Quando o jogo começa, um cronômetro começa a contar e quando o jogador terminar de encontrar os três personagens, ele pode enviar sua pontução/tempo. O jogador pode ver uma leaderboard com os 10 melhores tempos já atingidos.",
    projectsDesc4: "Esse projeto consiste na implementação do clássico jogo 'Batalha Naval'. Há 5 navios (tamanhos: 5, 4, 3, 2 e 1) para posicionar em um tabuleiro 10x10. Os navios inimigos são posicionados aleatoriamente. O jogo termina quando você acerta todos os navios inimigos ou quando o inimigo acerta todos os seus. Um dos projetos mais importantes para mim, que me ensinou que quando um projeto parace muito difícil, a melhor coisa a se fazer é me acalmar e dividir um problema grande em problemas menores, focando em uma coisa de cada vez.",
    projectsDesc5: "Consiste em uma página web que mostra a previsão do tempo usando a API OpenWeatherMap. O usuário pode procurar por qualquer local que quiser e checar informações tais como a situação do clima, temperatura, temperaturas mínimas e máximas, velocidade do vento e outros dados. O usuário também pode escolher entre celsius e farenheit para a exibição de informação de temperatura.",
    projectsDesc6: "Um projeto mais focado em ciência da computação e algoritmos. O projeto é uma solução para o problema do 'Caminho do Cavalo': Se temos um cavalo no quadrado A de um tabuleiro de xadrez, quantos movimentos ele precisa para chegar num quadrado B, e quais quadrados formam o caminho correto? O algoritmo criado para resolver este problema se baseia em teoria dos grafos.",
    projectsDesc7: "Consiste em uma página web para criar pixel art. Foi um dos meus primeiros projetos, quando ainda estava começando a focar em desenvolvimento web, e foi o primeiro projeto meu do qual eu realmente me orgulhei.",
    projectsBtnPreview: "Demonstração",
    projectsBtnCode: "Código",
    contactH2: "CONTATO",
    contactPara: "Obrigado por visitar meu portfólio! Se você tiver alguma ideia interessante de projeto ou oportunidade que gostaria de discutir, não hesite em entrar em contato. Eu adoraria te ouvir e ver como podemos colaborar.",
    footerLastUpdate: "ATUALIZADO PELA ÚLTIMA VEZ EM: 05/02/2023",
    footerCredits: "CRÉDITOS",
    footerCredits1: "Fotografia da tela inicial por ",
    footerCredits2: "Ícones por ",
    footerCredits3: "Logos por "
};

export const enText = {
    headerHome: "HOME",
    headerAbout: "ABOUT",
    headerProjects: "PROJECTS",
    headerContact: "CONTACT",
    homeMe: "Hi. I'm Guilherme Cantarino.",
    homeTitle: "Front-End Developer.",
    homeKnowMe: "Get to know me",
    aboutH2: "ABOUT",
    aboutDescription: "I am passionate about technology and even more passionate about learning. Since mid-2022 I've been studying front-end development. I have a strong grasp of the main concepts and I'm always trying to learn new technologies, improve on the technologies I already use and improve the way I organize and write my code in general. In addition, I am an extremely dedicated, responsible and organized person, and I take pleasure in giving my best in everything I do. I'm looking for my first professional experience, as a way to further develop my skills and contribute to the development of products that are useful for people.",
    aboutStackTitle: "Tech Stack & Tools",
    projectsH2: "PROJECTS",
    projectsDesc1: "Made with React.js and using Firebase for the Back-End. Prototype of a streaming platform highly inspired by Netflix.",
    projectsDesc2: "Made with React.js. This project consists of a Curriculum Vitae generator. The user enters his information and the application generates a Curriculum Vitae in pdf format. The user can enter personal information such as name, title, address, description, etc. The user can also enter as many professional and educational experiences as he wants.",
    projectsDesc3: "Made with React.js and using Firebase for the Back-End. Implementation of a game similar to 'Where's Wally?' Marvel Comics themed. There is a photo with several superheroes and the player needs to find three specific ones. When the game starts, a timer starts counting down and when the player has finished finding the three characters, he can submit his score/time. The player can see a leaderboard with the 10 best times ever achieved.",
    projectsDesc4: "This project consists of the implementation of the classic game 'Battleship'. There are 5 ships (sizes: 5, 4, 3, 2 and 1) to place on a 10x10 board. Enemy ships are randomly positioned. The game ends when you hit all enemy ships or when the enemy hits all of yours. One of the most important projects for me, which taught me that when a project seems too difficult, the best thing to do is to calm down and break a big problem into smaller problems, focusing on one thing at a time.",
    projectsDesc5: "It consists of a web page that shows the weather forecast using the OpenWeatherMap API. The user can search for any location he wants and check information such as the weather situation, temperature, minimum and maximum temperatures, wind speed and other data. The user can also choose between celsius and farenheit for displaying temperature information.",
    projectsDesc6: "A project more focused on computer science and algorithms. The project is a solution to the 'Knight's Path' problem: If we have a knight on square A of a chessboard, how many moves does it need to reach square B, and which squares form the correct path? The algorithm created to solve this problem is based on graph theory.",
    projectsDesc7: "It consists of a web page to create pixel art. It was one of my first projects, when I was still starting to focus on web development, and it was the first project of mine that I was really proud of.",
    projectsBtnPreview: "Live preview",
    projectsBtnCode: "Code",
    contactH2: "CONTACT",
    contactPara: "Thank you for visiting my portfolio! If you have any exciting project ideas or opportunities you'd like to discuss, please don't hesitate to reach out. I'd love to hear from you and see how we can collaborate.",
    footerLastUpdate: "LAST UPDATED: 05/02/2023",
    footerCredits: "CREDITS",
    footerCredits1: "Home picture by ",
    footerCredits2: "Icons by ",
    footerCredits3: "Logos by "
};